/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingId = IDL.Nat;
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const TimeSlotId = IDL.Nat;
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : BookingId,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'timeSlotId' : TimeSlotId,
  'paymentStatus' : PaymentStatus,
  'customerPhone' : IDL.Opt(IDL.Text),
  'specialRequests' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'updatedAt' : Time,
  'paymentId' : IDL.Opt(IDL.Text),
  'participantCount' : IDL.Nat,
  'totalPrice' : IDL.Nat,
  'customerEmail' : IDL.Text,
});
export const TimeSlot = IDL.Record({
  'id' : TimeSlotId,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'maxCapacity' : IDL.Nat,
  'date' : IDL.Text,
  'bookedCount' : IDL.Nat,
});
export const AdminStats = IDL.Record({
  'upcomingBookings' : IDL.Nat,
  'cancelledBookings' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'completedBookings' : IDL.Nat,
  'averageBookingValue' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'averageParticipants' : IDL.Nat,
});
export const SlotSummary = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'maxCapacity' : IDL.Nat,
  'bookedCount' : IDL.Nat,
});
export const DateSlotSummary = IDL.Record({
  'date' : IDL.Text,
  'totalBookings' : IDL.Nat,
  'slots' : IDL.Vec(SlotSummary),
  'totalCapacity' : IDL.Nat,
});
export const Coordinates = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
});
export const MeetingPoint = IDL.Record({
  'name' : IDL.Text,
  'instructions' : IDL.Text,
  'address' : IDL.Text,
  'landmark' : IDL.Opt(IDL.Text),
  'coordinates' : Coordinates,
});
export const TourPhoto = IDL.Record({
  'id' : IDL.Text,
  'alt' : IDL.Text,
  'url' : IDL.Text,
  'isPrimary' : IDL.Bool,
});
export const TourConfig = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'meetingPoint' : MeetingPoint,
  'maxCapacity' : IDL.Nat,
  'description' : IDL.Text,
  'included' : IDL.Vec(IDL.Text),
  'isActive' : IDL.Bool,
  'highlights' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
  'subtitle' : IDL.Text,
  'photos' : IDL.Vec(TourPhoto),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAllowedOrigin' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([BookingId], [Booking], []),
  'checkAvailability' : IDL.Func([TimeSlotId, IDL.Nat], [IDL.Bool], ['query']),
  'completeBooking' : IDL.Func([BookingId], [Booking], []),
  'confirmBooking' : IDL.Func([BookingId, IDL.Text], [Booking], []),
  'createBooking' : IDL.Func(
      [
        TimeSlotId,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [Booking],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [BookingId, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createTimeSlot' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [TimeSlot],
      [],
    ),
  'deleteTimeSlot' : IDL.Func([TimeSlotId], [IDL.Bool], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllSlots' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(TimeSlot)],
      ['query'],
    ),
  'getAllowedOrigins' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAvailableCapacity' : IDL.Func([TimeSlotId], [IDL.Nat], ['query']),
  'getAvailableSlots' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(TimeSlot)],
      ['query'],
    ),
  'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
  'getBookingStats' : IDL.Func([], [AdminStats], ['query']),
  'getBookingsByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getBookingsBySlot' : IDL.Func([TimeSlotId], [IDL.Vec(Booking)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmailKeyStatus' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getRevenueByPeriod' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'participantCount' : IDL.Nat,
          'totalRevenue' : IDL.Nat,
          'bookingCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getSenderEmail' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getSenderName' : IDL.Func([], [IDL.Text], ['query']),
  'getSlotsForCalendar' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(DateSlotSummary)],
      ['query'],
    ),
  'getStripeKeyStatus' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getTimeSlot' : IDL.Func([TimeSlotId], [IDL.Opt(TimeSlot)], ['query']),
  'getTourConfig' : IDL.Func([], [TourConfig], ['query']),
  'getTourDetails' : IDL.Func(
      [],
      [
        IDL.Record({
          'title' : IDL.Text,
          'duration' : IDL.Nat,
          'meetingPoint' : MeetingPoint,
          'maxCapacity' : IDL.Nat,
          'description' : IDL.Text,
          'included' : IDL.Vec(IDL.Text),
          'isActive' : IDL.Bool,
          'highlights' : IDL.Vec(IDL.Text),
          'photoCount' : IDL.Nat,
          'price' : IDL.Nat,
          'subtitle' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getUpcomingBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'healthCheck' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAllowedOrigin' : IDL.Func([IDL.Text], [], []),
  'sendBookingConfirmationEmail' : IDL.Func([BookingId], [IDL.Text], []),
  'sendTestEmail' : IDL.Func([IDL.Text], [IDL.Text], []),
  'setEmailApiKey' : IDL.Func([IDL.Text], [IDL.Text], []),
  'setSenderEmail' : IDL.Func([IDL.Text], [], []),
  'setSenderName' : IDL.Func([IDL.Text], [], []),
  'setStripeAuthorization' : IDL.Func([IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [
        IDL.Record({
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'updateMeetingPoint' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [MeetingPoint],
      [],
    ),
  'updateTimeSlot' : IDL.Func(
      [
        TimeSlotId,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
      ],
      [TimeSlot],
      [],
    ),
  'updateTourConfig' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(IDL.Bool),
      ],
      [TourConfig],
      [],
    ),
  'verifyAndConfirmBooking' : IDL.Func([IDL.Text, BookingId], [Booking], []),
  'whoami' : IDL.Func([], [IDL.Principal], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingId = IDL.Nat;
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const TimeSlotId = IDL.Nat;
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : BookingId,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'timeSlotId' : TimeSlotId,
    'paymentStatus' : PaymentStatus,
    'customerPhone' : IDL.Opt(IDL.Text),
    'specialRequests' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'updatedAt' : Time,
    'paymentId' : IDL.Opt(IDL.Text),
    'participantCount' : IDL.Nat,
    'totalPrice' : IDL.Nat,
    'customerEmail' : IDL.Text,
  });
  const TimeSlot = IDL.Record({
    'id' : TimeSlotId,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'maxCapacity' : IDL.Nat,
    'date' : IDL.Text,
    'bookedCount' : IDL.Nat,
  });
  const AdminStats = IDL.Record({
    'upcomingBookings' : IDL.Nat,
    'cancelledBookings' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'completedBookings' : IDL.Nat,
    'averageBookingValue' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'averageParticipants' : IDL.Nat,
  });
  const SlotSummary = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'maxCapacity' : IDL.Nat,
    'bookedCount' : IDL.Nat,
  });
  const DateSlotSummary = IDL.Record({
    'date' : IDL.Text,
    'totalBookings' : IDL.Nat,
    'slots' : IDL.Vec(SlotSummary),
    'totalCapacity' : IDL.Nat,
  });
  const Coordinates = IDL.Record({ 'lat' : IDL.Float64, 'lng' : IDL.Float64 });
  const MeetingPoint = IDL.Record({
    'name' : IDL.Text,
    'instructions' : IDL.Text,
    'address' : IDL.Text,
    'landmark' : IDL.Opt(IDL.Text),
    'coordinates' : Coordinates,
  });
  const TourPhoto = IDL.Record({
    'id' : IDL.Text,
    'alt' : IDL.Text,
    'url' : IDL.Text,
    'isPrimary' : IDL.Bool,
  });
  const TourConfig = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'meetingPoint' : MeetingPoint,
    'maxCapacity' : IDL.Nat,
    'description' : IDL.Text,
    'included' : IDL.Vec(IDL.Text),
    'isActive' : IDL.Bool,
    'highlights' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
    'subtitle' : IDL.Text,
    'photos' : IDL.Vec(TourPhoto),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAllowedOrigin' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([BookingId], [Booking], []),
    'checkAvailability' : IDL.Func(
        [TimeSlotId, IDL.Nat],
        [IDL.Bool],
        ['query'],
      ),
    'completeBooking' : IDL.Func([BookingId], [Booking], []),
    'confirmBooking' : IDL.Func([BookingId, IDL.Text], [Booking], []),
    'createBooking' : IDL.Func(
        [
          TimeSlotId,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [Booking],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [BookingId, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createTimeSlot' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [TimeSlot],
        [],
      ),
    'deleteTimeSlot' : IDL.Func([TimeSlotId], [IDL.Bool], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllSlots' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(TimeSlot)],
        ['query'],
      ),
    'getAllowedOrigins' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAvailableCapacity' : IDL.Func([TimeSlotId], [IDL.Nat], ['query']),
    'getAvailableSlots' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(TimeSlot)],
        ['query'],
      ),
    'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
    'getBookingStats' : IDL.Func([], [AdminStats], ['query']),
    'getBookingsByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getBookingsBySlot' : IDL.Func([TimeSlotId], [IDL.Vec(Booking)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmailKeyStatus' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getRevenueByPeriod' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'participantCount' : IDL.Nat,
            'totalRevenue' : IDL.Nat,
            'bookingCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getSenderEmail' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getSenderName' : IDL.Func([], [IDL.Text], ['query']),
    'getSlotsForCalendar' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(DateSlotSummary)],
        ['query'],
      ),
    'getStripeKeyStatus' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getTimeSlot' : IDL.Func([TimeSlotId], [IDL.Opt(TimeSlot)], ['query']),
    'getTourConfig' : IDL.Func([], [TourConfig], ['query']),
    'getTourDetails' : IDL.Func(
        [],
        [
          IDL.Record({
            'title' : IDL.Text,
            'duration' : IDL.Nat,
            'meetingPoint' : MeetingPoint,
            'maxCapacity' : IDL.Nat,
            'description' : IDL.Text,
            'included' : IDL.Vec(IDL.Text),
            'isActive' : IDL.Bool,
            'highlights' : IDL.Vec(IDL.Text),
            'photoCount' : IDL.Nat,
            'price' : IDL.Nat,
            'subtitle' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getUpcomingBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'healthCheck' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAllowedOrigin' : IDL.Func([IDL.Text], [], []),
    'sendBookingConfirmationEmail' : IDL.Func([BookingId], [IDL.Text], []),
    'sendTestEmail' : IDL.Func([IDL.Text], [IDL.Text], []),
    'setEmailApiKey' : IDL.Func([IDL.Text], [IDL.Text], []),
    'setSenderEmail' : IDL.Func([IDL.Text], [], []),
    'setSenderName' : IDL.Func([IDL.Text], [], []),
    'setStripeAuthorization' : IDL.Func([IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func(
        [
          IDL.Record({
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'updateMeetingPoint' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [MeetingPoint],
        [],
      ),
    'updateTimeSlot' : IDL.Func(
        [
          TimeSlotId,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
        ],
        [TimeSlot],
        [],
      ),
    'updateTourConfig' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(IDL.Bool),
        ],
        [TourConfig],
        [],
      ),
    'verifyAndConfirmBooking' : IDL.Func([IDL.Text, BookingId], [Booking], []),
    'whoami' : IDL.Func([], [IDL.Principal], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };