/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'upcomingBookings' : bigint,
  'cancelledBookings' : bigint,
  'totalBookings' : bigint,
  'completedBookings' : bigint,
  'averageBookingValue' : bigint,
  'totalRevenue' : bigint,
  'averageParticipants' : bigint,
}
export interface Booking {
  'id' : BookingId,
  'customerName' : string,
  'status' : BookingStatus,
  'timeSlotId' : TimeSlotId,
  'paymentStatus' : PaymentStatus,
  'customerPhone' : [] | [string],
  'specialRequests' : [] | [string],
  'createdAt' : Time,
  'updatedAt' : Time,
  'paymentId' : [] | [string],
  'participantCount' : bigint,
  'totalPrice' : bigint,
  'customerEmail' : string,
}
export type BookingId = bigint;
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface Coordinates { 'lat' : number, 'lng' : number }
export interface DateSlotSummary {
  'date' : string,
  'totalBookings' : bigint,
  'slots' : Array<SlotSummary>,
  'totalCapacity' : bigint,
}
export interface MeetingPoint {
  'name' : string,
  'instructions' : string,
  'address' : string,
  'landmark' : [] | [string],
  'coordinates' : Coordinates,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export interface SlotSummary {
  'id' : bigint,
  'startTime' : string,
  'endTime' : string,
  'maxCapacity' : bigint,
  'bookedCount' : bigint,
}
export type Time = bigint;
export interface TimeSlot {
  'id' : TimeSlotId,
  'startTime' : string,
  'endTime' : string,
  'maxCapacity' : bigint,
  'date' : string,
  'bookedCount' : bigint,
}
export type TimeSlotId = bigint;
export interface TourConfig {
  'title' : string,
  'duration' : bigint,
  'meetingPoint' : MeetingPoint,
  'maxCapacity' : bigint,
  'description' : string,
  'included' : Array<string>,
  'isActive' : boolean,
  'highlights' : Array<string>,
  'price' : bigint,
  'subtitle' : string,
  'photos' : Array<TourPhoto>,
}
export interface TourPhoto {
  'id' : string,
  'alt' : string,
  'url' : string,
  'isPrimary' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAllowedOrigin' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[BookingId], Booking>,
  'checkAvailability' : ActorMethod<[TimeSlotId, bigint], boolean>,
  'completeBooking' : ActorMethod<[BookingId], Booking>,
  'confirmBooking' : ActorMethod<[BookingId, string], Booking>,
  'createBooking' : ActorMethod<
    [TimeSlotId, string, string, [] | [string], bigint, [] | [string]],
    Booking
  >,
  'createCheckoutSession' : ActorMethod<[BookingId, string, string], string>,
  'createTimeSlot' : ActorMethod<[string, string, string, bigint], TimeSlot>,
  'deleteTimeSlot' : ActorMethod<[TimeSlotId], boolean>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllSlots' : ActorMethod<[string, string], Array<TimeSlot>>,
  'getAllowedOrigins' : ActorMethod<[], Array<string>>,
  'getAvailableCapacity' : ActorMethod<[TimeSlotId], bigint>,
  'getAvailableSlots' : ActorMethod<[string, string], Array<TimeSlot>>,
  'getBooking' : ActorMethod<[BookingId], [] | [Booking]>,
  'getBookingStats' : ActorMethod<[], AdminStats>,
  'getBookingsByEmail' : ActorMethod<[string], Array<Booking>>,
  'getBookingsBySlot' : ActorMethod<[TimeSlotId], Array<Booking>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmailKeyStatus' : ActorMethod<[], [] | [string]>,
  'getRevenueByPeriod' : ActorMethod<
    [string, string],
    {
      'participantCount' : bigint,
      'totalRevenue' : bigint,
      'bookingCount' : bigint,
    }
  >,
  'getSenderEmail' : ActorMethod<[], [] | [string]>,
  'getSenderName' : ActorMethod<[], string>,
  'getSlotsForCalendar' : ActorMethod<[string, string], Array<DateSlotSummary>>,
  'getStripeKeyStatus' : ActorMethod<[], [] | [string]>,
  'getTimeSlot' : ActorMethod<[TimeSlotId], [] | [TimeSlot]>,
  'getTourConfig' : ActorMethod<[], TourConfig>,
  'getTourDetails' : ActorMethod<
    [],
    {
      'title' : string,
      'duration' : bigint,
      'meetingPoint' : MeetingPoint,
      'maxCapacity' : bigint,
      'description' : string,
      'included' : Array<string>,
      'isActive' : boolean,
      'highlights' : Array<string>,
      'photoCount' : bigint,
      'price' : bigint,
      'subtitle' : string,
    }
  >,
  'getUpcomingBookings' : ActorMethod<[], Array<Booking>>,
  'healthCheck' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeAllowedOrigin' : ActorMethod<[string], undefined>,
  'sendBookingConfirmationEmail' : ActorMethod<[BookingId], string>,
  'sendTestEmail' : ActorMethod<[string], string>,
  'setEmailApiKey' : ActorMethod<[string], string>,
  'setSenderEmail' : ActorMethod<[string], undefined>,
  'setSenderName' : ActorMethod<[string], undefined>,
  'setStripeAuthorization' : ActorMethod<[string], string>,
  'transform' : ActorMethod<
    [
      {
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'updateMeetingPoint' : ActorMethod<
    [string, string, number, number, string, [] | [string]],
    MeetingPoint
  >,
  'updateTimeSlot' : ActorMethod<
    [TimeSlotId, [] | [string], [] | [string], [] | [string], [] | [bigint]],
    TimeSlot
  >,
  'updateTourConfig' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
      [] | [Array<string>],
      [] | [Array<string>],
      [] | [boolean],
    ],
    TourConfig
  >,
  'verifyAndConfirmBooking' : ActorMethod<[string, BookingId], Booking>,
  'whoami' : ActorMethod<[], Principal>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];