/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type BookingId = bigint;
export interface TimeSlot {
    id: TimeSlotId;
    startTime: string;
    endTime: string;
    maxCapacity: bigint;
    date: string;
    bookedCount: bigint;
}
export type Time = bigint;
export interface SlotSummary {
    id: bigint;
    startTime: string;
    endTime: string;
    maxCapacity: bigint;
    bookedCount: bigint;
}
export interface DateSlotSummary {
    date: string;
    totalBookings: bigint;
    slots: Array<SlotSummary>;
    totalCapacity: bigint;
}
export interface Coordinates {
    lat: number;
    lng: number;
}
export type TimeSlotId = bigint;
export interface MeetingPoint {
    name: string;
    instructions: string;
    address: string;
    landmark?: string;
    coordinates: Coordinates;
}
export interface TourPhoto {
    id: string;
    alt: string;
    url: string;
    isPrimary: boolean;
}
export interface AdminStats {
    upcomingBookings: bigint;
    cancelledBookings: bigint;
    totalBookings: bigint;
    completedBookings: bigint;
    averageBookingValue: bigint;
    totalRevenue: bigint;
    averageParticipants: bigint;
}
export interface Booking {
    id: BookingId;
    customerName: string;
    status: BookingStatus;
    timeSlotId: TimeSlotId;
    paymentStatus: PaymentStatus;
    customerPhone?: string;
    specialRequests?: string;
    createdAt: Time;
    updatedAt: Time;
    paymentId?: string;
    participantCount: bigint;
    totalPrice: bigint;
    customerEmail: string;
}
export interface TourConfig {
    title: string;
    duration: bigint;
    meetingPoint: MeetingPoint;
    maxCapacity: bigint;
    description: string;
    included: Array<string>;
    isActive: boolean;
    highlights: Array<string>;
    price: bigint;
    subtitle: string;
    photos: Array<TourPhoto>;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid",
    refunded = "refunded",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addAllowedOrigin(origin: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelBooking(bookingId: BookingId): Promise<Booking>;
    checkAvailability(slotId: TimeSlotId, participantCount: bigint): Promise<boolean>;
    completeBooking(bookingId: BookingId): Promise<Booking>;
    confirmBooking(bookingId: BookingId, paymentId: string): Promise<Booking>;
    createBooking(timeSlotId: TimeSlotId, customerName: string, customerEmail: string, customerPhone: string | null, participantCount: bigint, specialRequests: string | null): Promise<Booking>;
    createCheckoutSession(bookingId: BookingId, successUrl: string, cancelUrl: string): Promise<string>;
    createTimeSlot(date: string, startTime: string, endTime: string, maxCapacity: bigint): Promise<TimeSlot>;
    deleteTimeSlot(slotId: TimeSlotId): Promise<boolean>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllSlots(startDate: string, endDate: string): Promise<Array<TimeSlot>>;
    getAllowedOrigins(): Promise<Array<string>>;
    getAvailableCapacity(slotId: TimeSlotId): Promise<bigint>;
    getAvailableSlots(startDate: string, endDate: string): Promise<Array<TimeSlot>>;
    getBooking(bookingId: BookingId): Promise<Booking | null>;
    getBookingStats(): Promise<AdminStats>;
    getBookingsByEmail(email: string): Promise<Array<Booking>>;
    getBookingsBySlot(slotId: TimeSlotId): Promise<Array<Booking>>;
    getCallerUserRole(): Promise<UserRole>;
    getEmailKeyStatus(): Promise<string | null>;
    getRevenueByPeriod(startDate: string, endDate: string): Promise<{
        participantCount: bigint;
        totalRevenue: bigint;
        bookingCount: bigint;
    }>;
    getSenderEmail(): Promise<string | null>;
    getSenderName(): Promise<string>;
    getSlotsForCalendar(startDate: string, endDate: string): Promise<Array<DateSlotSummary>>;
    getStripeKeyStatus(): Promise<string | null>;
    getTimeSlot(slotId: TimeSlotId): Promise<TimeSlot | null>;
    getTourConfig(): Promise<TourConfig>;
    getTourDetails(): Promise<{
        title: string;
        duration: bigint;
        meetingPoint: MeetingPoint;
        maxCapacity: bigint;
        description: string;
        included: Array<string>;
        isActive: boolean;
        highlights: Array<string>;
        photoCount: bigint;
        price: bigint;
        subtitle: string;
    }>;
    getUpcomingBookings(): Promise<Array<Booking>>;
    healthCheck(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    removeAllowedOrigin(origin: string): Promise<void>;
    sendBookingConfirmationEmail(bookingId: BookingId): Promise<string>;
    sendTestEmail(toEmail: string): Promise<string>;
    setEmailApiKey(key: string): Promise<string>;
    setSenderEmail(email: string): Promise<void>;
    setSenderName(name: string): Promise<void>;
    setStripeAuthorization(key: string): Promise<string>;
    transform(arg0: {
        response: {
            status: bigint;
            body: Uint8Array;
            headers: Array<{
                value: string;
                name: string;
            }>;
        };
    }): Promise<{
        status: bigint;
        body: Uint8Array;
        headers: Array<{
            value: string;
            name: string;
        }>;
    }>;
    updateMeetingPoint(name: string, address: string, lat: number, lng: number, instructions: string, landmark: string | null): Promise<MeetingPoint>;
    updateTimeSlot(slotId: TimeSlotId, date: string | null, startTime: string | null, endTime: string | null, maxCapacity: bigint | null): Promise<TimeSlot>;
    updateTourConfig(title: string | null, subtitle: string | null, description: string | null, duration: bigint | null, price: bigint | null, maxCapacity: bigint | null, highlights: Array<string> | null, included: Array<string> | null, isActive: boolean | null): Promise<TourConfig>;
    verifyAndConfirmBooking(sessionId: string, bookingId: BookingId): Promise<Booking>;
    whoami(): Promise<Principal>;
}
import type { Booking as _Booking, BookingId as _BookingId, BookingStatus as _BookingStatus, Coordinates as _Coordinates, MeetingPoint as _MeetingPoint, PaymentStatus as _PaymentStatus, Time as _Time, TimeSlot as _TimeSlot, TimeSlotId as _TimeSlotId, TourConfig as _TourConfig, TourPhoto as _TourPhoto, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addAllowedOrigin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAllowedOrigin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAllowedOrigin(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelBooking(arg0: BookingId): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return from_candid_Booking_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return from_candid_Booking_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkAvailability(arg0: TimeSlotId, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAvailability(arg0, arg1);
            return result;
        }
    }
    async completeBooking(arg0: BookingId): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.completeBooking(arg0);
                return from_candid_Booking_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeBooking(arg0);
            return from_candid_Booking_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async confirmBooking(arg0: BookingId, arg1: string): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmBooking(arg0, arg1);
                return from_candid_Booking_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmBooking(arg0, arg1);
            return from_candid_Booking_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBooking(arg0: TimeSlotId, arg1: string, arg2: string, arg3: string | null, arg4: bigint, arg5: string | null): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Booking_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Booking_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: BookingId, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createTimeSlot(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<TimeSlot> {
        if (this.processError) {
            try {
                const result = await this.actor.createTimeSlot(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTimeSlot(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteTimeSlot(arg0: TimeSlotId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTimeSlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTimeSlot(arg0);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSlots(arg0: string, arg1: string): Promise<Array<TimeSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSlots(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSlots(arg0, arg1);
            return result;
        }
    }
    async getAllowedOrigins(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllowedOrigins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllowedOrigins();
            return result;
        }
    }
    async getAvailableCapacity(arg0: TimeSlotId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableCapacity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableCapacity(arg0);
            return result;
        }
    }
    async getAvailableSlots(arg0: string, arg1: string): Promise<Array<TimeSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSlots(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSlots(arg0, arg1);
            return result;
        }
    }
    async getBooking(arg0: BookingId): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingStats();
            return result;
        }
    }
    async getBookingsByEmail(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByEmail(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByEmail(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsBySlot(arg0: TimeSlotId): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsBySlot(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsBySlot(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmailKeyStatus(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmailKeyStatus();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmailKeyStatus();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRevenueByPeriod(arg0: string, arg1: string): Promise<{
        participantCount: bigint;
        totalRevenue: bigint;
        bookingCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueByPeriod(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueByPeriod(arg0, arg1);
            return result;
        }
    }
    async getSenderEmail(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSenderEmail();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSenderEmail();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSenderName(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSenderName();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSenderName();
            return result;
        }
    }
    async getSlotsForCalendar(arg0: string, arg1: string): Promise<Array<DateSlotSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSlotsForCalendar(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSlotsForCalendar(arg0, arg1);
            return result;
        }
    }
    async getStripeKeyStatus(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeKeyStatus();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeKeyStatus();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimeSlot(arg0: TimeSlotId): Promise<TimeSlot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimeSlot(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimeSlot(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTourConfig(): Promise<TourConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getTourConfig();
                return from_candid_TourConfig_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTourConfig();
            return from_candid_TourConfig_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTourDetails(): Promise<{
        title: string;
        duration: bigint;
        meetingPoint: MeetingPoint;
        maxCapacity: bigint;
        description: string;
        included: Array<string>;
        isActive: boolean;
        highlights: Array<string>;
        photoCount: bigint;
        price: bigint;
        subtitle: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTourDetails();
                return from_candid_record_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTourDetails();
            return from_candid_record_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingBookings();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingBookings();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async healthCheck(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.healthCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healthCheck();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeAllowedOrigin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAllowedOrigin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAllowedOrigin(arg0);
            return result;
        }
    }
    async sendBookingConfirmationEmail(arg0: BookingId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendBookingConfirmationEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendBookingConfirmationEmail(arg0);
            return result;
        }
    }
    async sendTestEmail(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendTestEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendTestEmail(arg0);
            return result;
        }
    }
    async setEmailApiKey(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.setEmailApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setEmailApiKey(arg0);
            return result;
        }
    }
    async setSenderEmail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSenderEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSenderEmail(arg0);
            return result;
        }
    }
    async setSenderName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSenderName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSenderName(arg0);
            return result;
        }
    }
    async setStripeAuthorization(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeAuthorization(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeAuthorization(arg0);
            return result;
        }
    }
    async transform(arg0: {
        response: {
            status: bigint;
            body: Uint8Array;
            headers: Array<{
                value: string;
                name: string;
            }>;
        };
    }): Promise<{
        status: bigint;
        body: Uint8Array;
        headers: Array<{
            value: string;
            name: string;
        }>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateMeetingPoint(arg0: string, arg1: string, arg2: number, arg3: number, arg4: string, arg5: string | null): Promise<MeetingPoint> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMeetingPoint(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
                return from_candid_MeetingPoint_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMeetingPoint(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
            return from_candid_MeetingPoint_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTimeSlot(arg0: TimeSlotId, arg1: string | null, arg2: string | null, arg3: string | null, arg4: bigint | null): Promise<TimeSlot> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTimeSlot(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTimeSlot(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateTourConfig(arg0: string | null, arg1: string | null, arg2: string | null, arg3: bigint | null, arg4: bigint | null, arg5: bigint | null, arg6: Array<string> | null, arg7: Array<string> | null, arg8: boolean | null): Promise<TourConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTourConfig(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg8));
                return from_candid_TourConfig_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTourConfig(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg8));
            return from_candid_TourConfig_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyAndConfirmBooking(arg0: string, arg1: BookingId): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAndConfirmBooking(arg0, arg1);
                return from_candid_Booking_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAndConfirmBooking(arg0, arg1);
            return from_candid_Booking_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async whoami(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.whoami();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.whoami();
            return result;
        }
    }
}
function from_candid_BookingStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_MeetingPoint_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MeetingPoint): MeetingPoint {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TourConfig_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TourConfig): TourConfig {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TimeSlot]): TimeSlot | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    duration: bigint;
    meetingPoint: _MeetingPoint;
    maxCapacity: bigint;
    description: string;
    included: Array<string>;
    isActive: boolean;
    highlights: Array<string>;
    price: bigint;
    subtitle: string;
    photos: Array<_TourPhoto>;
}): {
    title: string;
    duration: bigint;
    meetingPoint: MeetingPoint;
    maxCapacity: bigint;
    description: string;
    included: Array<string>;
    isActive: boolean;
    highlights: Array<string>;
    price: bigint;
    subtitle: string;
    photos: Array<TourPhoto>;
} {
    return {
        title: value.title,
        duration: value.duration,
        meetingPoint: from_candid_MeetingPoint_n18(_uploadFile, _downloadFile, value.meetingPoint),
        maxCapacity: value.maxCapacity,
        description: value.description,
        included: value.included,
        isActive: value.isActive,
        highlights: value.highlights,
        price: value.price,
        subtitle: value.subtitle,
        photos: value.photos
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    instructions: string;
    address: string;
    landmark: [] | [string];
    coordinates: _Coordinates;
}): {
    name: string;
    instructions: string;
    address: string;
    landmark?: string;
    coordinates: Coordinates;
} {
    return {
        name: value.name,
        instructions: value.instructions,
        address: value.address,
        landmark: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.landmark)),
        coordinates: value.coordinates
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    duration: bigint;
    meetingPoint: _MeetingPoint;
    maxCapacity: bigint;
    description: string;
    included: Array<string>;
    isActive: boolean;
    highlights: Array<string>;
    photoCount: bigint;
    price: bigint;
    subtitle: string;
}): {
    title: string;
    duration: bigint;
    meetingPoint: MeetingPoint;
    maxCapacity: bigint;
    description: string;
    included: Array<string>;
    isActive: boolean;
    highlights: Array<string>;
    photoCount: bigint;
    price: bigint;
    subtitle: string;
} {
    return {
        title: value.title,
        duration: value.duration,
        meetingPoint: from_candid_MeetingPoint_n18(_uploadFile, _downloadFile, value.meetingPoint),
        maxCapacity: value.maxCapacity,
        description: value.description,
        included: value.included,
        isActive: value.isActive,
        highlights: value.highlights,
        photoCount: value.photoCount,
        price: value.price,
        subtitle: value.subtitle
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    customerName: string;
    status: _BookingStatus;
    timeSlotId: _TimeSlotId;
    paymentStatus: _PaymentStatus;
    customerPhone: [] | [string];
    specialRequests: [] | [string];
    createdAt: _Time;
    updatedAt: _Time;
    paymentId: [] | [string];
    participantCount: bigint;
    totalPrice: bigint;
    customerEmail: string;
}): {
    id: BookingId;
    customerName: string;
    status: BookingStatus;
    timeSlotId: TimeSlotId;
    paymentStatus: PaymentStatus;
    customerPhone?: string;
    specialRequests?: string;
    createdAt: Time;
    updatedAt: Time;
    paymentId?: string;
    participantCount: bigint;
    totalPrice: bigint;
    customerEmail: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_BookingStatus_n5(_uploadFile, _downloadFile, value.status),
        timeSlotId: value.timeSlotId,
        paymentStatus: from_candid_PaymentStatus_n7(_uploadFile, _downloadFile, value.paymentStatus),
        customerPhone: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.customerPhone)),
        specialRequests: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.specialRequests)),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        paymentId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.paymentId)),
        participantCount: value.participantCount,
        totalPrice: value.totalPrice,
        customerEmail: value.customerEmail
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : "refunded" in value ? PaymentStatus.refunded : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n3(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<string> | null): [] | [Array<string>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
